### ISSUE TITLE
Flag --enable-external-secret-stores causes panic errors

### ISSUE THREAD

**Issue by stdmje** [upbound/provider-vault#11]
### What happened?

When adding --enable-external-secret-stores flag to the provider ControllerConfig, the provider pod crashes.

```
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault {"level":"info","ts":"2023-08-31T12:15:29Z","logger":"provider-vault","msg":"Alpha feature enabled","flag":"EnableAlphaExternalSecretStores"}
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault panic: runtime error: invalid memory address or nil pointer dereference
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cd4bf3]
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault goroutine 1 [running]:
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault github.com/upbound/provider-vault/internal/controller/ad/secretbackend.Setup({0x26a3640, 0xc00019b6c0}, {{{0x2695990, 0xc0000006d8}, {0x2695330, 0xc00049c458}, 0x8bb2c97000, 0xa, 0xc000051ca0, 0x0}, ...})
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault 	github.com/upbound/provider-vault/internal/controller/ad/secretbackend/zz_controller.go:31 +0x2f3
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault github.com/upbound/provider-vault/internal/controller.Setup({0x26a3640, 0xc00019b6c0}, {{{0x2695990, 0xc0000006d8}, {0x2695330, 0xc00049c458}, 0x8bb2c97000, 0xa, 0xc000051ca0, 0x0}, ...})
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault 	github.com/upbound/provider-vault/internal/controller/zz_setup.go:269 +0x81f
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault main.main()
provider-vault-7d7075831d4d-7d8cc768f9-wcv2l provider-vault 	github.com/upbound/provider-vault/cmd/provider/main.go:120 +0x21e8
```

### How can we reproduce it?

Create a ControllerConfig:

```
 apiVersion: pkg.crossplane.io/v1alpha1
 kind: ControllerConfig
 metadata:
   name: vault
   annotations:
    argocd.argoproj.io/sync-wave: "0"   
 spec:
  args:
    - --enable-external-secret-stores

```

and then the provider

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  controllerConfigRef:
    name: vault
  package: xpkg.upbound.io/upbound/provider-vault:v0.2.0
```
