### ISSUE TITLE
Create SecretV2 example

### ISSUE THREAD

**Issue by ichasco-heytrade** [upbound/provider-vault#19]
Hi!

I have tried to create a secret with `SecretV2` api kind but I am not able to do it.

Is there any complete example in de documentation? I only found this:
https://github.com/upbound/provider-vault/blob/main/examples/kvsecretv2/kvsecretv2.yaml

But there is not any reference to the secret yaml. And I have tried to create it by my own and I get this error:
```
cannot run refresh: refresh failed: json: cannot unmarshal string into Go value of type map[string]interface {}:
```

Created Secret template:

```
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.kv.name }}-{{ .Values.kv.secretName }}-secret"
data:
  data-key: {{ toJson (tpl .Values.kv.key .) | b64enc }} 
```

the value is:
```
  key: |
    {
      "sentry.dsn": "test"
    }
```

And the `SecretV2`

```
apiVersion: {{ .Values.kv.apiVersion }}
kind: SecretV2
metadata:
  name: "{{ .Values.kv.name }}-{{ .Values.kv.secretName }}-secret"
spec:
  providerConfigRef:
    name: {{ .Values.kv.providerConfigName }}
  forProvider:
    dataJsonSecretRef:
      name: "{{ .Values.kv.name }}-{{ .Values.kv.secretName }}-secret"
      key: data-key 
      namespace: crossplane
    mount: {{ .Values.kv.env }}
    name: "{{ .Values.kv.name }}/{{ .Values.kv.secretName }}"
```

Thanks!
