### ISSUE TITLE
Reading a secret from vault

### ISSUE THREAD

**Issue by AMNKramer** [upbound/provider-vault#28]
### What happened?
I want to read a secret from vault, only watching it, not taking control of it. 
Not 100% sure if this provider is meant to do that, as it's lacking documentation. Though I think it should be, as the terraform module it is based on can do that. 
From the API it looks like it could be possible but every `Secret` object requires `dataJsonSecretRef` (for writing the secret). 

Though the API documentation does not label this field as mandatory, in fact it is as following error occurs when applying without it:
```
The Secret "test" is invalid: spec: Invalid value: "object": dataJsonSecretRef is a required parameter
```

### How to reproduce:
```
apiVersion: generic.vault.upbound.io/v1alpha1
kind: Secret
metadata:
  name: test
spec:
  forProvider:
    path: "kv/some/path"
  providerConfigRef:
    name: vault-provider-config
```

### What environment did it happen in?
Version 0.3.0 of the provider.

**Comment by jonasz-lasut** [comment]
Tested on a local v4 build against kv-v1 and kv-v2 mounts: Ready within a second, connection secret populated, Vault version counter unchanged, control without the annotation fails with `external resource does not exist`, deleting the MR leaves the Vault secret in place.

This works today with an observe-only managed resource, and I have just verified it on a current v4 build against both a kv-v1 and a kv-v2 mount. Two details are not obvious from the CRD.

1. `dataJsonSecretRef` is only required when the resource may write. The CRD enforces it with a validation rule that applies to management policies containing `*`, `Create`, or `Update`, so with `managementPolicies: ["Observe"]` you can leave it out. The error you quoted comes from v0.3.0, where the field was unconditionally required.
2. The provider identifies the Vault secret by the `crossplane.io/external-name` annotation, not by `spec.forProvider.path`, and observe-only resources need that annotation to import. Without it the resource stays `SYNCED=False` with `observe failed: external resource does not exist`. Set it to the same value as `path`. Use the logical path (for example `kv/some/path`); the resource detects a kv-v2 mount and inserts `/data/` itself.

```yaml
apiVersion: generic.vault.upbound.io/v1alpha1
kind: Secret
metadata:
  name: some-path
  annotations:
    crossplane.io/external-name: kv/some/path
spec:
  managementPolicies: ["Observe"]
  forProvider:
    path: kv/some/path
  writeConnectionSecretToRef:
    name: some-path-data
    namespace: crossplane-system
  providerConfigRef:
    name: vault-provider-config
```

The secret's contents are sensitive, so they do not appear in `status.atProvider`. They are published to the connection secret instead: each key becomes `attribute.data.<key>`, and the whole document is available as `attribute.data_json`. For a Vault secret `{"username": "alice", "password": "..."}` the connection secret holds `attribute.data.username`, `attribute.data.password`, and `attribute.data_json`. Leave `disableRead` unset (false), otherwise nothing is read. With `Observe` as the only policy the provider never writes or deletes the Vault secret, and deleting the managed resource leaves it in place.

Management policies are on by default in current releases (`--enable-management-policies` defaults to true). Keep in mind that the resource re-reads the Vault secret once per poll interval (10 minutes by default); for continuous syncing of many secrets, External Secrets Operator or Vault Secrets Operator is a better fit.
