### ISSUE TITLE
Unable to create a namespace in vault enterprise

### ISSUE THREAD

**Issue by kamalverma1** [upbound/provider-vault#31]
### What happened?
I am unable to create a namespace in vault-enterprise setup on kubernetes. It shows created while applying the yaml but it never gets created. 

### How can we reproduce it?

1. Install upbound provider-vault v0.4.0..
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-vault
spec:
  package: xpkg.upbound.io/upbound/provider-vault:v0.4.0
```
2. Create a secret with vault token with below yaml. Refer to the example [here](https://github.com/upbound/provider-vault/blob/main/examples/providerconfig/secret.yaml.tmpl).
```
apiVersion: v1
kind: Secret
metadata:
  name: vault-provider-token
  namespace: vault-ns
type: Opaque
stringData:
  credentials: |
    {
      "token_name": "vault-creds-test-token",
      "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
```

4. Create a providerConfig with below yaml. Refer to the example [here](https://github.com/upbound/provider-vault/blob/main/examples/providerconfig/providerconfig.yaml).
```
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
  namespace: vault-ns
spec:
  address: "https://vault-domain"
  credentials:
    source: Secret
    secretRef:
      name: vault-provider-token
      namespace: vault-enterprise
      key: credentials
```

I used the below yaml to create a namespace as per the example shared [here](https://github.com/upbound/provider-vault/blob/main/examples-generated/vault/namespace.yaml). 

```
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Namespace
metadata:
  name: ns1
spec:
  forProvider:
    path: ns1
  providerConfigRef:
    name: "vault-provider-config"
```
$~ kubectl get namespaces.vault.vault.upbound.io
```
NAME         READY   SYNCED   EXTERNAL-NAME   AGE
ns1                                           1h
```
$~ kubectl get namespaces.vault.vault.upbound.io ns1
```
Error from server (NotFound): the server could not find the requested resource (get namespaces.vault.vault.upbound.io ns1)
```

### What environment did it happen in?
Nonprod environment
