### ISSUE TITLE
k8s auth backend -- no authbackend type

### ISSUE THREAD

**Issue by reedjosh** [upbound/provider-vault#32]
### What happened?
Tried to create a kubernetes auth backend.

Used [authBackendConfig](https://doc.crds.dev/github.com/upbound/provider-vault/kubernetes.vault.upbound.io/AuthBackendConfig/v1alpha1@v0.4.0)

But there is then no path for that backend.

`Errors:\n\n* no handler for route 'auth/k8s-test-cluster/config': "`

Most other backends have an authbackend type.

In terraform I'd do something like:

```
resource "vault_auth_backend" "kubernetes" {
  type = "kubernetes"
  path = "k8s-${local.cluster_name}"
}
```
Which would create the backend.

I'm going to try using the token backend, but not sure if that will work, and it seems a bit odd that this doesn't exist for the k8s backend.

Thanks!

**Comment by reedjosh** [comment]
Well, that was quick.

I see the following in the generated examples.

``` yaml
apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/authbackendconfig
  labels:
    testing.upbound.io/example-name: kubernetes
  name: kubernetes
spec:
  forProvider:
    type: kubernetes
```

Suppose I'll go give that a try. : )
