### ISSUE TITLE
Reference Accessor of oidc auth backend in groupAlias

### ISSUE THREAD

**Issue by kamalverma1** [upbound/provider-vault#36]
### What problem are you facing?
There should be a way to reference the accessor for the oidc method and also the canonicalId of groups while creating a group Alias. This is an issue if the Resource is created by a seperate claim.

### How could Upbound help solve your problem?
Add somthing similar to Data Source in in [terraform](https://registry.terraform.io/providers/hashicorp/vault/2.9.0/docs/data-sources/auth_backend). Maybe somthing similar to referencing VPCID [in this doc.](https://docs.crossplane.io/latest/concepts/managed-resources/)

For example:
```
apiVersion: identity.vault.upbound.io/v1alpha1
kind: GroupAlias
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupalias
  labels:
    testing.upbound.io/example-name: group-alias
  name: cld-csm-admins-sg-kdtesting
spec:
  deletionPolicy: Delete
  forProvider:
    namespace: mytestns
    canonicalIdRef: 
      name: <mytestgroup>
    mountAccessorRef: 
      name: <oidc-auth-backend-name> 
    name: <group-ObjectId>
    ----
```

**Comment by tschlaepfer** [comment]
Agree, would very much like this :)

**Comment by tschlaepfer** [comment]
I have created a draft MR for this feature, however, I'm not used to Go nor creating Crossplane providers so I would need some support. Right now I'm still struggling with the code to create a reference for different AuthBackend types. 
```
# config.go
....
r.References["mount_accessor"] = config.Reference{
    Type: "github.com/upbound/provider-vault/apis/jwt/v1alpha1.AuthBackend",
    Extractor: common.AccessorExtractor,
}
```
Do to the way the Terraform code for HashiCorp Vault has been written one would need to be able to configure multiple types here. 

Could someone from the maintainers guide me on how this should be implemented?

**Comment by jonasz-lasut** [comment]
Thank you for opening the issue @tschlaepfer 

Two separate asks here with different answers.

**`canonicalId` from a Group.** This already works: `GroupAlias` has `canonicalIdRef` and `canonicalIdSelector`, which resolve against `identity.vault.upbound.io Group` and take its id:

```yaml
spec:
  forProvider:
    canonicalIdRef:
      name: my-test-group
```

**`mountAccessor` from an oidc `AuthBackend`.** This is the same request as #60. A reference field in Crossplane can only target one kind, decided at build time. `mountAccessorRef` targets `auth.vault.upbound.io Backend` because that is what the upstream Terraform example uses, and there is no way to make one ref field accept `jwt.vault.upbound.io AuthBackend` as well, which is where the draft in the second comment got stuck. The recommended approach is to resolve the accessor in the Composition: patch `status.atProvider.accessor` from the `AuthBackend` into `spec.forProvider.mountAccessor` of the `GroupAlias`, with a `Required` policy so the alias waits for the backend. The Crossplane project settled this in crossplane/crossplane#1770 and crossplane/upjet#95: multi-kind references are provided at the Composition layer, not on managed resources. A full function-patch-and-transform example is in #60.
