### ISSUE TITLE
oidcDiscoveryCaPem

### ISSUE THREAD

**Issue by phac008** [upbound/provider-vault#45]
hi!

Env:
Vault 1.17.2
provider: v1.0.0
Keycloak 25.0.2

authbackend.jwt.vault.upbound.io has setting oidcDiscoveryCaPem to change system CA to custom CA

regarding https://developer.hashicorp.com/vault/api-docs/auth/jwt#oidc_discovery_ca_pem content is required, not file name.

in cli I can use oidcDiscoveryCaPem=@ca.pem, then oidc backend creation works.
with authbackend.jwt.vault.upbound.io @ca.pem doesn't work - any ideas to get this working?

**Comment by phac008** [comment]
i try to push this - may with new release there are more possibilities to solve this?

**Comment by jonasz-lasut** [comment]
Hi @phac008 thank you for opening the issue

`oidcDiscoveryCaPem` takes the certificate content, not a file name. The `@ca.pem` form is a Vault CLI convenience that reads the file on your machine before sending the request. The provider runs in a pod with no access to that file, so the same string is sent to Vault literally and fails validation.

Put the PEM into the field as a YAML block scalar:

```yaml
apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackend
metadata:
  name: keycloak
spec:
  forProvider:
    type: oidc
    path: oidc
    oidcDiscoveryUrl: https://keycloak.example.com/realms/vault
    oidcClientId: vault
    oidcClientSecretSecretRef:
      name: keycloak-client
      namespace: crossplane-system
      key: client_secret
    oidcDiscoveryCaPem: |
      -----BEGIN CERTIFICATE-----
      MIIDdzCCAl+gAwIBAgIEAgAAuTANBgkqhkiG9w0BAQUFADBaMQswCQYDVQQGEwJJ
      ...
      -----END CERTIFICATE-----
  providerConfigRef:
    name: default
```

The field is not marked sensitive in the Terraform schema, so there is no `oidcDiscoveryCaPemSecretRef` variant. If you would rather not inline the certificate in the manifest, a composition can patch the value in from another resource.

You can also try mounting the files to the provider pod and using `@` notation but I've not tried this approach. Closing as inline PEM is the only supported mode of operations for this provider and upstream terraform provider
