### ISSUE TITLE
Observe failed when upgrading to v2.0.0

### ISSUE THREAD

**Issue by bakito** [upbound/provider-vault#49]
### What happened?
I'm creating kubernetes AuthBackendRole and vault Policy resources with crossplane.

This worked fine with version v1.0.0.
After Upgrading to v2.0.0 both resources can not by synced any more with the following error:

`observe failed: failed to observe the resource: [{0 no vault token set on Client  []}]`

### How can we reproduce it?
Provider Config:

```
apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
spec:
  address: https://vault.foo.ch
  credentials:
    secretRef:
      key: credentials
      name: vault-auth
      namespace: crossplane-system
    source: Secret
```
Policy :

```
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: vault-secret-store-config-cgmjg
spec:
  deletionPolicy: Delete
  forProvider:
    name: team-ns-secret-store
    policy: |
      path "My/Path/*" {
        capabilities = ["read"]
      }
  initProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: vault-provider-config
```
AuthBackendRole
```
apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: vault-secret-store-config-cgmjg
spec:
  deletionPolicy: Delete
  forProvider:
    aliasNameSource: serviceaccount_uid
    backend: k8s
    boundServiceAccountNames:
      - vault-secret-store
    boundServiceAccountNamespaces:
      - my-ns
    roleName: team-ns-secret-store
    tokenPolicies:
      - team-ns-secret-store
    tokenTtl: 3600
    tokenType: default
  initProvider: {}
  managementPolicies:
    - '*'
  providerConfigRef:
    name: vault-provider-config

```

### What environment did it happen in?
crossplane: v1.18.1
provider vault: v2.0.0
