### ISSUE TITLE
Version 2.0.1 seems to be broken

### ISSUE THREAD

**Issue by KevinWang15** [upbound/provider-vault#52]
```yaml
apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackend
metadata:
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
  name: jwt-xxx
spec:
  deletionPolicy: Delete
  forProvider:
    boundIssuer: https://container.googleapis.com/v1/projects/xxx/locations/asia-southeast1-a/clusters/xxx
    oidcDiscoveryUrl: https://container.googleapis.com/v1/projects/xxx/locations/asia-southeast1-a/clusters/xxx
    path: xxx
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
```

On version 2.0.1

It would error with

```yaml
  status:
    atProvider: {}
    conditions:
    - lastTransitionTime: "2025-01-13T08:51:58Z"
      reason: Creating
      status: "False"
      type: Ready
    - lastTransitionTime: "2025-01-13T10:01:37Z"
      message: "observe failed: failed to observe the resource: [{0 Error making API
        request.\n\nURL: GET https://xxx/v1/sys/mounts/auth/xxx\nCode:
        405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n  []}]"
      reason: ReconcileError
      status: "False"
      type: Synced
    - lastTransitionTime: "2025-01-13T08:52:00Z"
      message: |-
        async create failed: failed to create the resource: [{0 error updating configuration to Vault for path jwt-xxx: Error making API request.

        URL: PUT https://xxx/v1/auth/xxx/config
        Code: 400. Errors:

        * error checking oidc discovery URL: 404 Not Found: {
          "error": {
            "code": 404,
            "message": "Requested entity was not found.",
            "status": "NOT_FOUND"
          }
        }
          []}]
      reason: AsyncCreateFailure
      status: "False"
      type: LastAsyncOperation
```

I switched back to 1.0.0, and the same spec could be created without a problem
