### ISSUE TITLE
GroupAlias mountAccessorRef & mountAccessorSelector do not support AuthBackend as a target

### ISSUE THREAD

**Issue by andrewseling** [upbound/provider-vault#60]
### What happened?

The [GroupAlias](https://marketplace.upbound.io/providers/upbound/provider-vault/v2.1.1/resources/identity.vault.upbound.io/GroupAlias/v1alpha1) Kind can take a mountAccessor value in three ways:

1. Direct input (mountAccessor)
2. Name reference (mountAccessorRef)
3. Selector reference (mountAccessorSelector)

All three options work with the [Backend](https://marketplace.upbound.io/providers/upbound/provider-vault/v2.1.1/resources/auth.vault.upbound.io/Backend/v1alpha1) Kind.

Vault also uses various `AuthBackend` Kinds, such as the [JWT AuthBackend](https://marketplace.upbound.io/providers/upbound/provider-vault/v2.1.1/resources/jwt.vault.upbound.io/AuthBackend/v1alpha1), which enables SSO auth via OIDC.

Passing the accessor ID of the AuthBackend directly to GroupAlias works as expected. 

Passing the accessor ID via either:

2. Name reference
3. Selector reference

Does not work, as the provider looks for the regular `Backend` Kind rather than `AuthBackend`.

I've created a small composition using the go-templating composition function to retrieve the value of the `AuthBackend` accessor and pass it to the `GroupAlias` `mountAccessor` field directly as a workaround.

I would like `GroupAlias` to support both `Backend` and `AuthBackend` Kinds for reference lookups, to eliminate the need for this composition and simplify the user experience.

### How can we reproduce it?

1. Create an [AuthBackend](https://marketplace.upbound.io/providers/upbound/provider-vault/v2.1.1/resources/jwt.vault.upbound.io/AuthBackend/v1alpha1) in Vault. Take note of the accessor ID in the GUI/CLI.
2. Create a [GroupAlias](https://marketplace.upbound.io/providers/upbound/provider-vault/v2.1.1/resources/identity.vault.upbound.io/GroupAlias/v1alpha1) resource, passing the accessor ID directly to the `mountAccessor` field. This should work.
3. Update the `GroupAlias` to use `mountAccessorRef` and receive an error. Note that the missing reference is to the regular `Backend` kind instead of `AuthBackend`.

### What environment did it happen in?

Crossplane: v1.18
Vault provider: 2.0.1

**Comment by ryantking** [comment]
@Eldaroth not OP, but I used a similar workaround, here's an excerpt from my composition that creates a JWT auth backend and then grabs the accessor to configure in the group aliases:

```yaml
            ---
            apiVersion: jwt.vault.m.upbound.io/v1alpha1
            kind: AuthBackend
            metadata:
              name: my-backend
              namespace: vault
              annotations:
                {{ setResourceNameAnnotation "vault-oidc-authbackend" }}
            spec:
                # ...
            {{- end }}

            ---
            apiVersion: jwt.vault.m.upbound.io/v1alpha1
            kind: AuthBackendRole
            metadata:
              name: my-backend-role
              namespace: vault
              annotations:
                {{ setResourceNameAnnotation "vault-oidc-authbackendrole" }}
            spec:
                 # ...

            {{- $vaultOidcBackend := getComposedResource . "vault-oidc-authbackend" -}}
            {{- if $vaultOidcBackend.status.atProvider.accessor -}}
            {{- $mountAccessor := $vaultOidcBackend.status.atProvider.accessor -}}
            {{- $vaultStatus = set $vaultStatus "oidcMountAccessor" $mountAccessor }}

            {{- range $group := $vaultGroups }}
            ---
            apiVersion: identity.vault.m.upbound.io/v1alpha1
            kind: GroupAlias
            metadata:
              name: my-backend-{{ $group.id }}
              namespace: vault
              annotations:
                {{ setResourceNameAnnotation (printf "%s-vault-groupalias" $group.id) }}
            spec:
              forProvider:
                name: {{ $group.name }}
                canonicalIdRef:
                  name: {{ $group.id }}
                mountAccessor: {{ $mountAccessor }} 
            {{- end -}}

            ---
            apiVersion: mygroup/v1alpha1
            kind: MyKind
            status:
              vault:
                {{- $vaultStatus | toYaml | nindent 4 }}
```

This creates the AuthBackend, uses `getComposedResource` to load the resource, waits for the status to be populated, loads the mount accessor from the status, and then uses it to create the group aliases. It also stores the accessor as the XR status so other compositions can load it using function-extra-resources or function-go-template's builtin extra resource loading. Note: function-go-template  can only load cluster scoped resources until [this](https://github.com/crossplane-contrib/function-go-templating/pull/498) gets merged.

**Comment by jonasz-lasut** [comment]
Thanks you for the clear report @andrewseling. This is a limitation of how Crossplane cross-resource references work rather than a provider bug, so here is what is going on and what I recommend.

**Why `mountAccessorRef` only resolves auth `Backend`.** Crossplane references are resolved by code generated at build time, and each reference field targets exactly one kind. upjet derives the target for `mount_accessor` from the upstream Terraform example, which uses `vault_auth_backend.github.accessor`, so the generated resolver lists `Backend.auth.vault.upbound.io` and reads its `status.atProvider.accessor`. Pointing the same ref at a `jwt.vault.upbound.io AuthBackend` can never work, whatever name or labels you give it. Six kinds in this provider expose an accessor (`auth Backend` plus the `jwt`, `github`, `ldap`, `okta` and `gcp` `AuthBackend`s), and the Crossplane resource model has no polymorphic reference that could cover them with one field. The same limitation shows up in other providers, for example GCP `URLMap.defaultService` or AWS CloudWatch alarm actions. The Crossplane project considered generic, multi-kind references in crossplane/crossplane#1770 and closed it in 2023 with the decision to provide this at the Composition layer rather than in managed resources; crossplane/upjet#95 was closed with the same conclusion. So this is the intended design, not a gap waiting for a provider-side fix.

**Recommended approach: resolve it in the Composition.** Every `AuthBackend` exposes the accessor at `status.atProvider.accessor`, so a Composition can carry it from the backend into the alias. The go-templating and extra-resources snippets above do exactly that. With function-patch-and-transform it is two patches, one from the backend into the XR status and one from the XR status into the alias:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vault-oidc-groups
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XVaultOIDC
  mode: Pipeline
  pipeline:
    - step: resources
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: oidc-backend
            base:
              apiVersion: jwt.vault.upbound.io/v1alpha1
              kind: AuthBackend
              spec:
                forProvider:
                  type: oidc
                  path: oidc
                  # ...
            patches:
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.accessor
                toFieldPath: status.oidcAccessor
          - name: admins-alias
            base:
              apiVersion: identity.vault.upbound.io/v1alpha1
              kind: GroupAlias
              spec:
                forProvider:
                  name: cld-csm-admins
                  canonicalIdRef:
                    name: admins
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: status.oidcAccessor
                toFieldPath: spec.forProvider.mountAccessor
                policy:
                  fromFieldPath: Required
```

`policy.fromFieldPath: Required` holds the alias back until the backend has reported its accessor, so it is never created with an empty `mountAccessor`. The XRD needs a `status.oidcAccessor` string field. The same pattern works for the namespaced `*.vault.m.upbound.io` kinds and for `EntityAlias`, which has no reference field on `mountAccessor` at all today.
