### ISSUE TITLE
Allow secrets in non-json-format for the provider

### ISSUE THREAD

**Issue by RickardCardell** [upbound/provider-vault#70]
### What problem are you facing?

The provider-vault can only read a secret that is in json-format. Secrets created from a resource using e.g. `writeConnectionSecretToRef` or just a plain secret, can't be used directly, but has to be transformed to json in some way (how?). 

I.e. a secret written by [provider-azure-dbforpostgresql FlexibleServer](https://marketplace.upbound.io/providers/upbound/provider-azure-dbforpostgresql/v1.11.1/resources/dbforpostgresql.azure.upbound.io/FlexibleServer/v1beta1#doc:spec-writeConnectionSecretToRef) that can't be read by the provider-vault:

```
 apiVersion: v1
 kind: Secret
 data:
   attribute.administrator_password: ZHVtbXktcGFzcyB3YXMK
   endpoint: QUJCQSB3YXMgaGVyZQo=
   password: ZHVtbXktcGFzcyB3YXMK
   port: NDIK
   username: TktPVEIK
 metadata:
   name: postgresql-connection-secrets
   namespace: default
 type: connection.crossplane.io/v1alpha1
```
Also not accepted by the provider-vault:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: a_token
  namespace: upbound-system
type: Opaque
stringData:
  token: QUJCQSB3YXMgaGVyZQo=
```

Currently workarounds has to be made to transform the secrets so that the vault-provider can be used.

### How could Upbound help solve your problem?

Introduce a more user-friendly API for the provider-vault which allows it to read secrets in "key-value" formats as above.

**Comment by jonasz-lasut** [comment]
Hi @RickardCardell thank you for opening the issue and for detailed examples. The short version: the single-key JSON shape is inherited from the Terraform provider that provider-vault is generated from, and the place to adapt a key/value Secret to it is a Composition, not the provider.

**Why the provider wants JSON.** provider-vault is generated with upjet from the HashiCorp Terraform Vault provider. Its `vault_kv_secret_v2` and `vault_generic_secret` resources take the secret contents as a single `data_json` attribute, a JSON-encoded object in one string. upjet maps that sensitive string attribute to `dataJsonSecretRef`, which points at exactly one key of one Kubernetes Secret and passes its value through unchanged. There is no Terraform attribute that accepts a map, so there is nothing for the provider to map a multi-key Secret onto. Accepting a whole Secret would be a hand-written, provider-specific field outside the generated schema. We keep the official providers aligned with the upstream Terraform schema, and this kind of data conversion belongs to the Composition layer, which is also where the Crossplane project has placed cross-resource data plumbing in general.

**Recommended approach: build the JSON in the Composition.** A composition function can turn the connection details of another composed resource into the Secret the `SecretV2` needs. With function-go-templating on Crossplane v2, composing the intermediate `Secret` directly:

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgres-to-vault
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XDatabase
  mode: Pipeline
  pipeline:
    - step: render
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            ---
            apiVersion: dbforpostgresql.azure.m.upbound.io/v1beta1
            kind: FlexibleServer
            metadata:
              annotations:
                {{ setResourceNameAnnotation "server" }}
            spec:
              forProvider:
                # ...
              writeConnectionSecretToRef:
                name: {{ .observed.composite.resource.metadata.name }}-server
            {{- if ne $.observed.resources nil }}
            {{- if index $.observed.resources "server" }}
            {{- with getComposedConnectionDetails . "server" }}
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ $.observed.composite.resource.metadata.name }}-vault-input
              annotations:
                {{ setResourceNameAnnotation "vault-input" }}
            stringData:
              data_json: {{ dict "username" (index . "username" | b64dec) "password" (index . "password" | b64dec) "endpoint" (index . "endpoint" | b64dec) | toJson | quote }}
            ---
            apiVersion: kv.vault.m.upbound.io/v1alpha1
            kind: SecretV2
            metadata:
              annotations:
                {{ setResourceNameAnnotation "vault-secret" }}
            spec:
              forProvider:
                mount: kv
                name: databases/{{ $.observed.composite.resource.metadata.name }}
                dataJsonSecretRef:
                  name: {{ $.observed.composite.resource.metadata.name }}-vault-input
                  key: data_json
              providerConfigRef:
                name: default
            {{- end }}
            {{- end }}
            {{- end }}
```

`getComposedConnectionDetails` returns the composed resource's connection details base64-encoded, hence `b64dec`; `toJson` produces the document `data_json` expects. The intermediate `Secret` and the `SecretV2` only render once the server has reported its connection details, so nothing is written to Vault with placeholder values. Crossplane v2 composes plain Kubernetes objects such as this `Secret` directly; if your Crossplane service account is not allowed to manage Secrets, grant it with an aggregated ClusterRole as described in the Compositions documentation.

The same works for an `Opaque` Secret created outside the Composition, like your second example: request it as a required resource (`ExtraResources` in function-go-templating) and build `data_json` from its `data` the same way.
