### ISSUE TITLE
Enable option to "Use annotations of JWT service account as alias metadata" kubernetes auth Configuration

### ISSUE THREAD

**Issue by devang704** [upbound/provider-vault#79]
### What problem are you facing?

I am using upbound provider vault to configure vault kubernetes auth method, and I want to use templated policy which use custom metadata be supplied from Kubernetes annotations on the ServiceAccount. For which we need to enable option "Use annotations of JWT service account as alias metadata" for kubernetes auth method. 

I have tried to configure the Vault Kubernetes auth method using Upbound provider, specifically using the `kind: AuthBackendConfig`, but I can't find the appropriate configuration option.

### How could Upbound help solve your problem?
Allow to enable/disable "Use annotations of JWT service account as alias metadata" option by below parameter.

e.g:

```
apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendConfig
metadata:
  name: vault-k8s-auth-config
spec:
  forProvider:
    backend: kubernetes
    parameters:
      kubernetesHost: https://kubernetes.default.svc
      useServiceAccountAnnotations: true  # Critical parameter for alias metadata
  ... 
```
