### ISSUE TITLE
group already exists

### ISSUE THREAD

**Issue by jkleinlercher** [upbound/provider-vault#83]
### What happened?
Sometimes when creating a new group the managed resource gets unhealthy with „already exists“ message. This is the the status of this resource in ArgoCD:

```
  - group: identity.vault.upbound.io
    health:
      message: 'create failed: async create failed: failed to create the resource:
        [{0 failed to create identity group "team1", reason=group already exists with
        path="/identity/group/name/team1", id="95dcce1f-79a7-7699-ad84-2f1c19676ef2"  []}]'
```

Epic #

### How can we reproduce it?

We cannot reproduce it permanently. It happens in 2 of 10 cases.

### What environment did it happen in?

crossplane 1.19
crossplane vault provider 2.1.2
vault 1.18.1

**Comment by jkleinlercher** [comment]
Sometimes I am also faced with other „already exists“ issues like

```
  - group: vault.vault.upbound.io
    health:
      message: |-
        create failed: async create failed: failed to create the resource: [{0 error enabling audit backend: Error making API request.

        URL: PUT http://sx-vault-active.vault.svc.cluster.local:8200/v1/sys/audit/file
        Code: 400. Errors:

        * path already in use: invalid configuration  []}]
      status: Degraded
    kind: Audit
    name: audit
    status: Synced
    syncWave: 1
    version: v1alpha1
```
